### ISSUE TITLE
10.3.2 Compiler Error

### ISSUE THREAD

**Issue by MayoZelaya** [RRUZ/vcl-styles-utils#252]
Hi,
Unable to compile with Rad Studio 10.3.2. getting the following error on Vcl.Styles.Ext Line 373.
[dcc32 Error] Vcl.Styles.Ext.pas(373): E2361 Cannot access private symbol TStyleManager.TSourceInfo

Thanks in advance

**Comment by djjd47130** [comment]
I haven't tried 10.3.2 yet, but I'm guessing that support was dropped. I'm still on 10.1 Berlin, and this is just fine.

**Comment by MayoZelaya** [comment]
Hi,

Changed TStyleManager.TSourceInfo to TSourceInfo and now it works ok.

Maybe compiler fix/bug/change.

**Comment by vekunz** [comment]
With this solution we now have a compilation error with Delphi XE5
